name: Crear Ranking de Licitaciones

on:
  workflow_dispatch:
  repository_dispatch:
    types: [execute_workflow]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Correr Script Licitaciones
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: python your_script.py

      - name: Guardar archivo de log
        if: always()  # Esto asegura que el paso se ejecute incluso si otros pasos fallan
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: your_script.log  # Asegúrate de que este nombre coincida con el nombre del archivo .log que estás generando
      

      - name: Output Success Message
        run: echo "Script ejecutado correctamente en GitHub Actions."
